[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

via_ir = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]

[rpc_endpoints]
blast_sepolia = "${BLAST_SEPOLIA_RPC}"

[etherscan]
blast_sepolia = { key = "${BLASTSCAN_API_KEY}", chain = "168587773", url = "${BLASTSCAN_API_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
